version: "3.7"
services:
  web:
    image: animal-crossing-graphql
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
    ports: 
      - "3000:3000"

